version: '3.7'
services:
  backend:
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - APP_SETTINGS=config.DevelopmentConfig

  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    env_file:
      - .env2
    environment:
      - HOST=0.0.0.0
    links:
      - "backend:backend"
    