#!/bin/bash

grn=$'\e[1;32m'
yel=$'\e[1;33m'
cyn=$'\e[1;36m'
end=$'\e[0m'

git checkout staging
printf "%s\n" "${cyn}Superproject${end} repository ${grn}successfully${end} checked out ${yel}staging${end} branch!"
cd backend
git fetch
git checkout staging
printf "%s\n" "${cyn}Backend${end} repository ${grn}successfully${end} checked out ${yel}staging${end} branch!"
cd ../frontend
git fetch
git checkout staging
printf "%s\n" "${cyn}Frontend${end} repository ${grn}successfully${end} checked out ${yel}staging${end} branch!"
cd ..