#!/bin/bash

grn=$'\e[1;32m'
yel=$'\e[1;33m'
cyn=$'\e[1;36m'
end=$'\e[0m'

git fetch
git checkout staging --
printf "%s\n" "${cyn}powwow-capstone/spacemonitor${end} repository ${grn}successfully${end} checked out its ${yel}staging${end} branch!"
cd backend
git fetch
git checkout staging --
git submodule update --remote --merge
printf "%s\n" "${cyn}powwow-capstone/backend${end} submodule ${grn}successfully${end} checked out and updated its ${yel}staging${end} branch!"
cd ../frontend
git fetch
git checkout staging --
git submodule update --remote --merge
printf "%s\n" "${cyn}powwow-capstone/frontend${end} submodule ${grn}successfully${end} checked out and updated its ${yel}staging${end} branch!"
cd ..